<?php
/**
* Implements hook_permission()  
*/
function nodeview_permission() {
    return array(
        'access mynode' => array(
        'title' => t('Gives access to "nodeview" module'),
        'description' => t('Perform administration tasks for "nodeview" module.'),
        ),
    );
}



/**
* Implements hook_menu()
*/  
function nodeview_menu(){
    $items = array();
    $items ['mynode'] = array(
        'title' => 'Node View',    
        'page callback' => 'nodeview_node_view',
        'access arguments' => array('access mynode'), 
        'weight' => 12, );
    return $items;            
}
 
function nodeview_node_view($node, $view_mode = 'full', $langcode) {
    if($view_mode == 'full') {
        if(empty($_SESSION['node_views'][$node->nid])) {
            $_SESSION['node_views'][$node->nid] = 0;
        }

        //increments view count with 1  
        $_SESSION['node_views'][$node->nid]++;

        //placeholder to pass to total_view_count
        $total_view_count = array(
            '%total_views' => $_SESSION['node_views'][$node->nid],
            );

        $node->content['node_views'] = array(
            '#markup' => t('You have viewed this page %num times', $total_view_count),
            '#weight' => 10;
        );
    }
}

function nodeview_get_record($nid, $uid){
    $query = db_select('nodeview', 'nv')
        ->fields('nv', array('nid', 'uid', 'current_view_count', 'total_view_count', 'time'))
        ->condition('nid', $nid)
        ->condition('uid', $uid);
    $record = $query->execute()->fetch();
    return $record;
}

function nodeview_set_record($record){
    if(!is+object($record)) {
        return watchdog('nodeview', 'No update about node view', array(), WATCHDOG_ERROR);
    }

    $query = db_merge('nodeview')
        ->key(array('nid'=>$record->nid))
        ->key(array('uid'=>$record->uid))
        ->fields((array) $record);
    $query->execute();    
}
